// Mock data for the CAP & PIP Consequence Management System

const employees = [
  {
    ohrId: "OHR-204871",
    name: "Aarav Mehta",
    email: "aarav.mehta@example.com",
    type: "regular",
    supervisor: "Priya Shah",
    manager: "Rohan Iyer",
    team: "Claims Ops",
  },
  {
    ohrId: "OHR-204912",
    name: "Sneha Kulkarni",
    email: "sneha.k@example.com",
    type: "apprentice",
    supervisor: "Priya Shah",
    manager: "Rohan Iyer",
    team: "Claims Ops",
  },
  {
    ohrId: "OHR-205033",
    name: "Marcus Bennett",
    email: "m.bennett@example.com",
    type: "regular",
    supervisor: "David Cole",
    manager: "Helena Park",
    team: "Underwriting",
  },
  {
    ohrId: "OHR-205117",
    name: "Liana Cortez",
    email: "l.cortez@example.com",
    type: "regular",
    supervisor: "David Cole",
    manager: "Helena Park",
    team: "Underwriting",
  },
  {
    ohrId: "OHR-205221",
    name: "Devansh Rao",
    email: "d.rao@example.com",
    type: "apprentice",
    supervisor: "Priya Shah",
    manager: "Rohan Iyer",
    team: "Claims Ops",
  },
  {
    ohrId: "OHR-205398",
    name: "Olivia Tan",
    email: "o.tan@example.com",
    type: "regular",
    supervisor: "Marcia Lin",
    manager: "Helena Park",
    team: "Customer Care",
  },
  {
    ohrId: "OHR-205502",
    name: "Kabir Joshi",
    email: "k.joshi@example.com",
    type: "regular",
    supervisor: "Marcia Lin",
    manager: "Helena Park",
    team: "Customer Care",
  },
  {
    ohrId: "OHR-888123",
    name: "Marcus Wright",
    email: "marcus.w@example.com",
    type: "regular",
    supervisor: "David Cole",
    manager: "Helena Park",
    team: "Underwriting",
  },
  {
    ohrId: "OHR-999456",
    name: "Grace Harper",
    email: "grace.h@example.com",
    type: "regular",
    supervisor: "Marcia Lin",
    manager: "Helena Park",
    team: "Customer Care",
  },
  {
    ohrId: "OHR-205600",
    name: "Dani Ramos",
    email: "dani.r@example.com",
    type: "regular",
    supervisor: "Marcia Lin",
    manager: "Helena Park",
    team: "Customer Care",
  },
];

export const pipCandidates = [
  {
    employee: employees[0],
    consecutiveWarnings: 3,
    warningsLast8Weeks: 5,
    niLastMonth: 1,
    niLast6Months: 2,
    triggerMet: true, // Assuming this is a boolean, not a date
    identifiedAt: "2026-04-28",
    supervisorAcknowledged: false,
  },
  {
    employee: employees[4],
    consecutiveWarnings: 2,
    warningsLast8Weeks: 6,
    niLastMonth: 0,
    niLast6Months: 2,
    triggerMet: true, // Assuming this is a boolean, not a date
    identifiedAt: "2026-04-29",
    supervisorAcknowledged: true,
  },
  {
    employee: employees[5],
    consecutiveWarnings: 3,
    warningsLast8Weeks: 4,
    niLastMonth: 1,
    niLast6Months: 1,
    triggerMet: true, // Assuming this is a boolean, not a date
    identifiedAt: "2026-05-01",
    supervisorAcknowledged: false,
  },
];

export const pipCases = [
  {
    id: "PIP-2025-0142",
    employee: employees[2],
    status: "active",
    startDate: "2026-03-18",
    endDate: "2026-06-17",
    duration: 60,
    triggerReason: "3 consecutive warnings + 2 NI ratings (last 6 months)",
    consecutiveWarnings: 3,
    warningsLast8Weeks: 6,
    niLastMonth: 1,
    niLast6Months: 2,
    targets: [
      "Maintain QA score ≥ 92%",
      "Average handle time ≤ 6:30",
      "Zero compliance breaches",
      "Attendance 100%",
    ],
    reviews: [
      {
        number: 1, // Assuming this is a number, not a date
        date: "2026-04-02",
        status: "met",
        kpiScore: 93,
        feedback: "Improved on QA. Continue focus on AHT.",
        targets: ["QA ≥ 92%"],
      },
      {
        number: 2, // Assuming this is a number, not a date
        date: "2026-04-17",
        status: "not-met",
        kpiScore: 88,
        feedback: "QA dropped. Discussed root causes.",
        targets: ["QA ≥ 92%"],
      },
      { number: 3, date: "2026-05-10", status: "met", kpiScore: 94, feedback: "Strong recovery." },
      { number: 4, date: "2026-06-01", status: "scheduled" },
    ],
    acknowledgmentEmail: "RE_PIP_Acknowledgement_OHR-205033.eml",
    acknowledgedAt: "2026-03-19",
    documentVersion: 3,
    extended: false,
  },
  {
    id: "PIP-2025-0138",
    employee: employees[3],
    status: "extended",
    startDate: "2026-02-20",
    endDate: "2026-05-21",
    duration: 90,
    triggerReason: "6 warnings (last 8 weeks) + 1 NI rating (last month)",
    consecutiveWarnings: 2,
    warningsLast8Weeks: 6,
    niLastMonth: 1,
    niLast6Months: 1,
    targets: ["QA ≥ 90%", "AHT ≤ 7:00", "CSAT ≥ 4.4"],
    reviews: [ // Assuming these are numbers, not dates
      { number: 1, date: "2026-02-28", status: "not-met", kpiScore: 85 },
      { number: 2, date: "2026-03-15", status: "met", kpiScore: 91 },
      { number: 3, date: "2026-03-30", status: "not-met", kpiScore: 86 },
      { number: 4, date: "2026-04-21", status: "not-met", kpiScore: 87 },
      { number: 5, date: "2026-05-06", status: "met", kpiScore: 92 },
      { number: 6, date: "2026-05-21", status: "scheduled" },
    ],
    documentVersion: 6,
    extended: true,
    acknowledgedAt: "2026-02-21",
    acknowledgmentEmail: "RE_PIP_Acknowledgement_OHR-205117.eml",
  },
  {
    id: "PIP-2025-0150",
    employee: employees[1],
    status: "pending-approval",
    startDate: "2026-04-01",
    endDate: "2026-06-30",
    duration: 60,
    triggerReason: "3 consecutive warnings + 1 NI rating (last month)",
    consecutiveWarnings: 3,
    warningsLast8Weeks: 4,
    niLastMonth: 1,
    niLast6Months: 1,
    targets: ["QA ≥ 88%", "AHT ≤ 7:30"],
    reviews: [ // Assuming these are numbers, not dates
      { number: 1, date: "2026-04-10", status: "not-met", kpiScore: 82 },
      { number: 2, date: "2026-04-25", status: "not-met", kpiScore: 85 },
      { number: 3, date: "2026-05-10", status: "not-met", kpiScore: 84 },
      { number: 4, date: "2026-05-25", status: "not-met", kpiScore: 86 },
    ],
    documentVersion: 4,
    extended: false,
    acknowledgedAt: "2026-04-02",
    acknowledgmentEmail: "RE_PIP_Acknowledgement_OHR-204912.eml",
  },
  {
    id: "PIP-2025-0121",
    employee: employees[6],
    status: "closed-success",
    startDate: "2026-01-10",
    endDate: "2026-03-11",
    duration: 60,
    triggerReason: "6 warnings (last 8 weeks) + 2 NI ratings (last 6 months)",
    consecutiveWarnings: 2,
    warningsLast8Weeks: 6,
    niLastMonth: 0,
    niLast6Months: 2,
    targets: ["QA ≥ 90%"],
    reviews: [ // Assuming these are numbers, not dates
      { number: 1, date: "2026-01-20", status: "met", kpiScore: 92 },
      { number: 2, date: "2026-02-05", status: "met", kpiScore: 93 },
      { number: 3, date: "2026-02-20", status: "not-met", kpiScore: 88 },
      { number: 4, date: "2026-03-11", status: "met", kpiScore: 94 },
    ],
    documentVersion: 4,
    extended: false,
    acknowledgedAt: "2026-01-11",
    acknowledgmentEmail: "RE_PIP_Acknowledgement_OHR-205502.eml",
  },
];

export const capCases = [
  // Existing CAP cases, updated to 2026
  {
    id: "CAP-2025-0481",
    employee: employees[0],
    level: "CAP 1",
    status: "accepted",
    breachType: "Data Handling",
    breachDescription: "Shared customer PII over unsecured channel during peak shift.",
    raisedBy: "Nikhil Anand",
    raisedByTeam: "QA",
    raisedAt: "2026-04-22",
    auditMonth: "2026-04",
    validUntil: "2026-07-21",
    disputeAttempts: 0,
    exceptionRequested: false,
    history: [
      { date: "2026-04-22", event: "CAP logged (pending)", actor: "Nikhil Anand (QA)" },
      { date: "2026-04-22", event: "Email sent to supervisor; CC managers + you", actor: "System" },
      { date: "2026-04-23", event: "Supervisor accepted", actor: "Priya Shah (Supervisor)" },
      { date: "2026-04-24", event: "Discussion scheduled with guide", actor: "Priya Shah (Supervisor)" },
      { date: "2026-04-24", event: "Discussion closed", actor: "Priya Shah (Supervisor)" },
      { date: "2026-04-24", event: "CAP letter generated & issued", actor: "System" },
      { date: "2026-04-25", event: "Agent acknowledged letter", actor: "Aarav Mehta (Agent)" },
      { date: "2026-04-26", event: "CAP status moved to active", actor: "System" },
    ],
    acknowledgedAt: "2026-04-25",
  },
  {
    id: "CAP-2025-0492",
    employee: employees[3],
    level: "CAP 2",
    status: "disputed",
    breachType: "Compliance — Process Deviation",
    breachDescription: "Bypassed mandatory verification step on 4 cases.",
    raisedBy: "Sara Iqbal",
    raisedByTeam: "Compliance",
    raisedAt: "2026-04-27",
    auditMonth: "2026-04",
    validUntil: "2026-07-26",
    disputeAttempts: 1,
    exceptionRequested: false,
    history: [
      { date: "2026-04-27", event: "CAP logged (pending)", actor: "Sara Iqbal (Compliance)" },
      { date: "2026-04-27", event: "Email sent to supervisor; CC managers + you", actor: "System" },
      { date: "2026-04-28", event: "Supervisor disputed (1/2)", actor: "David Cole (Supervisor)" },
      { date: "2026-04-29", event: "Offline discussion logged", actor: "Sara Iqbal (Compliance)" },
    ],
  },
  {
    id: "CAP-2025-0467",
    employee: employees[5],
    level: "CAP 3",
    status: "hr-escalation",
    breachType: "Repeat Misconduct",
    breachDescription: "Third occurrence of unauthorized system access.",
    raisedBy: "Sara Iqbal",
    raisedByTeam: "Compliance",
    raisedAt: "2026-04-15",
    auditMonth: "2026-04",
    validUntil: "2026-07-14",
    disputeAttempts: 0,
    exceptionRequested: false,
    history: [
      { date: "2026-04-15", event: "CAP logged (pending)", actor: "Sara Iqbal (Compliance)" },
      { date: "2026-04-15", event: "Email sent to supervisor; CC managers + you", actor: "System" },
      { date: "2026-04-16", event: "Supervisor accepted", actor: "Marcia Lin (Supervisor)" },
      { date: "2026-04-17", event: "Discussion scheduled", actor: "Marcia Lin (Supervisor)" },
      { date: "2026-04-18", event: "Discussion closed", actor: "Marcia Lin (Supervisor)" },
      { date: "2026-04-18", event: "Escalated to HR", actor: "System" },
    ],
    acknowledgedAt: "2026-04-17",
  },
  {
    id: "CAP-2025-0501",
    employee: employees[6],
    level: "CAP 1",
    status: "exception-pending",
    breachType: "Quality — Documentation",
    breachDescription: "Incomplete case notes flagged across audit sample.",
    raisedBy: "Nikhil Anand",
    raisedByTeam: "QA",
    raisedAt: "2026-05-01",
    auditMonth: "2026-05",
    validUntil: "2026-07-30",
    disputeAttempts: 0,
    exceptionRequested: true,
    exceptionApprover: "Helena Park (SDL)",
    history: [
      { date: "2026-05-01", event: "CAP logged (pending)", actor: "Nikhil Anand (QA)" },
      { date: "2026-05-01", event: "Email sent to supervisor; CC managers + you", actor: "System" },
      { date: "2026-05-02", event: "Supervisor raised exception", actor: "Marcia Lin (Supervisor)" },
      { date: "2026-05-02", event: "Supporting docs uploaded (2)", actor: "Marcia Lin (Supervisor)" },
    ],
  },
  {
    id: "CAP-2025-0455",
    employee: employees[2],
    level: "CAP 2",
    status: "closed",
    breachType: "Compliance — Disclosure",
    breachDescription: "Failed to disclose conflict of interest within SLA.",
    raisedBy: "Sara Iqbal",
    raisedByTeam: "Compliance",
    raisedAt: "2026-03-08",
    auditMonth: "2026-03",
    validUntil: "2026-06-06",
    disputeAttempts: 2,
    exceptionRequested: false,
    history: [
      { date: "2026-03-08", event: "CAP logged (pending)", actor: "Sara Iqbal (Compliance)" },
      { date: "2026-03-08", event: "Email sent to supervisor; CC managers + you", actor: "System" },
      { date: "2026-03-10", event: "Supervisor accepted", actor: "David Cole (Supervisor)" },
      { date: "2026-03-11", event: "Discussion scheduled", actor: "David Cole (Supervisor)" },
      { date: "2026-03-14", event: "Discussion closed", actor: "David Cole (Supervisor)" },
      { date: "2026-03-14", event: "CAP letter generated & issued", actor: "System" },
      { date: "2026-03-16", event: "Agent acknowledged letter", actor: "Marcus Bennett (Agent)" },
      { date: "2026-03-16", event: "CAP status moved to active", actor: "System" },
      { date: "2026-03-18", event: "Case closed", actor: "System" },
    ],
    acknowledgedAt: "2026-03-16",
  },
  // Dummy Warning Letters (from cases.index.jsx and cap/index.jsx)
  {
    id: "WL-2026-010",
    employee: employees[0], // Aarav Mehta
    breachType: "LOW-Legal/Procedural - Product Cancelation Disclosure",
    raisedByTeam: "Compliance",
    raisedAt: "2026-01-10",
    auditMonth: "2026-01",
    validUntil: "2026-04-10",
    level: "Warning",
    status: "closed",
    disputeAttempts: 0,
    exceptionRequested: false,
    history: [
      { date: "2026-01-10", event: "Warning letter logged (pending)", actor: "Compliance Team" },
      { date: "2026-01-10", event: "Email sent to supervisor; CC managers + you", actor: "System" },
      { date: "2026-01-12", event: "Supervisor accepted", actor: "Priya Shah (Supervisor)" },
      { date: "2026-01-14", event: "Discussion scheduled", actor: "Priya Shah (Supervisor)" },
      { date: "2026-01-15", event: "Discussion closed", actor: "Priya Shah (Supervisor)" },
      { date: "2026-01-15", event: "Warning letter generated & status closed", actor: "System" },
      { date: "2026-01-16", event: "Agent acknowledged", actor: "Aarav Mehta (Agent)" },
    ],
  },
  {
    id: "WL-2026-012",
    employee: employees[7], // Marcus Wright
    breachType: "Quality — Call Disclosure",
    raisedByTeam: "Compliance",
    raisedAt: "2026-05-15",
    auditMonth: "2026-05",
    validUntil: "2026-08-15",
    level: "Warning",
    status: "accepted",
    disputeAttempts: 0,
    exceptionRequested: false,
    history: [{ date: "2026-05-15", event: "Warning Letter issued", actor: "QA Team" }],
  },
  {
    id: "WL-2026-015",
    employee: employees[8], // Grace Harper
    breachType: "Misc Fee Usage",
    raisedByTeam: "QA",
    raisedAt: "2026-05-20",
    auditMonth: "2026-05",
    validUntil: "2026-08-20",
    level: "Warning",
    status: "logged",
    disputeAttempts: 0,
    exceptionRequested: false,
    history: [{ date: "2026-05-20", event: "Warning Letter issued", actor: "Compliance Team" }],
  },
  // Specific CAPs/WL for OHR-204871 (Aarav Mehta) from new.jsx
  {
    id: "CAP-2026-01",
    employee: employees[0], // Aarav Mehta
    breachType: "HIGH-Legal/Procedural - Standard MGR codes not used",
    level: "CAP 1",
    status: "closed",
    raisedAt: "2026-05-01",
    auditMonth: "2026-05",
    validUntil: "2026-07-30",
    disputeAttempts: 0,
    exceptionRequested: false,
    history: [{ date: "2026-05-01", event: "CAP logged", actor: "System" }],
  },
  {
    id: "CAP-2026-03",
    employee: employees[0], // Aarav Mehta
    breachType: "Compliance — Call Disconnections",
    level: "CAP 2",
    status: "accepted",
    raisedAt: "2026-03-15",
    auditMonth: "2026-03",
    validUntil: "2026-06-13",
    disputeAttempts: 0,
    exceptionRequested: false,
    history: [{ date: "2026-03-15", event: "CAP logged", actor: "System" }],
  },
  {
    id: "CAP-2026-11",
    employee: employees[0], // Aarav Mehta
    breachType: "Compliance — RONA",
    level: "CAP 1",
    status: "closed",
    raisedAt: "2026-11-22",
    auditMonth: "2026-11",
    validUntil: "2027-02-20",
    disputeAttempts: 0,
    exceptionRequested: false,
    history: [{ date: "2026-11-22", event: "CAP logged", actor: "System" }],
  },
  {
    id: "WL-2026-088",
    employee: employees[0], // Aarav Mehta
    breachType: "HIGH-Legal/Procedural - Refund not applicable however processed", // This is a QA breach type
    level: "Warning",
    status: "accepted",
    raisedAt: "2026-10-05",
    auditMonth: "2026-10",
    validUntil: "2027-01-03",
    disputeAttempts: 0,
    exceptionRequested: false,
    history: [{ date: "2026-10-05", event: "Warning Letter issued", actor: "System" }],
  },
  // Dummy cases from disputes.jsx
  {
    id: "CAP-2026-005",
    employee: employees[0], // Sarah Connor (Aarav Mehta)
    breachType: "Compliance — Zero Cart",
    raisedBy: "John Smith",
    raisedByTeam: "QA",
    level: "CAP 1",
    status: "disputed",
    raisedAt: "2026-05-01",
    auditMonth: "2026-05",
    validUntil: "2026-07-30",
    disputeAttempts: 1,
    documents: ["workload_report.pdf", "system_health_check.png"],
    supervisorComment: "Agent was managing double the usual volume during this hour. CRM performance was also degraded.",
    history: [{ date: "2026-05-01", event: "CAP logged", actor: "John Smith" }],
  },
  {
    id: "CAP-2026-009",
    employee: employees[3], // Kyle Reese (Liana Cortez)
    breachType: "Compliance — Long Holds",
    raisedBy: "John Smith",
    raisedByTeam: "Compliance",
    level: "CAP 2",
    status: "exception-pending",
    raisedAt: "2026-05-10",
    auditMonth: "2026-05",
    validUntil: "2026-08-08",
    exceptionApprover: "QA Manager",
    documents: ["internet_outage_ticket.pdf"],
    supervisorComment: "Regional outage reported. Documented by IT department and SDL was informed.",
    history: [{ date: "2026-05-01", event: "CAP logged", actor: "John Smith" }],
  },
  {
    id: "CAP-2026-021",
    employee: employees[9], // Dani Ramos
    breachType: "Compliance — Call Disconnections",
    raisedBy: "Sarah Miller",
    raisedByTeam: "QA",
    level: "CAP 3",
    status: "disputed",
    raisedAt: "2026-05-12",
    auditMonth: "2026-05",
    validUntil: "2026-08-10",
    disputeAttempts: 1,
    documents: ["crm_error_screenshots.zip"],
    supervisorComment: "CRM force-closed due to API errors at the customer end.",
    history: [{ date: "2026-05-01", event: "CAP logged", actor: "Sarah Miller" }],
  },
];

export function findEmployee(ohrId) {
  return employees.find((e) => e.ohrId.toLowerCase() === ohrId.toLowerCase());
}

export function getEmployees() {
  return employees;
}

export function getCAPHistoryForEmployee(ohrId) {
  return capCases.filter((c) => c.employee.ohrId === ohrId);
}

export function recommendCAPLevel(ohrId, breachType) {
  const past = getCAPHistoryForEmployee(ohrId);
  const sameBreach = past.filter((c) => c.breachType === breachType);
  if (sameBreach.length >= 2) return "CAP 3";
  if (sameBreach.length === 1) return "CAP 2";
  if (past.length >= 2) return "CAP 2";
  return "CAP 1";
}

export const departments = [
  {
    name: "C3 Support",
    channel: "voice",
    headcount: 142,
    activePIP: 6,
    openCAP: 9,
    manager: "Rohan Iyer",
  },
  {
    name: "Website Security Support",
    channel: "voice",
    headcount: 88,
    activePIP: 3,
    openCAP: 5,
    manager: "Helena Park",
  },
  {
    name: "The Ranch",
    channel: "voice",
    headcount: 64,
    activePIP: 2,
    openCAP: 4,
    manager: "Marcia Lin",
  },
  {
    name: "Messaging - India General",
    channel: "messaging",
    headcount: 120,
    activePIP: 5,
    openCAP: 7,
    manager: "Rohan Iyer",
  },
  {
    name: "Messaging - RoW General",
    channel: "messaging",
    headcount: 96,
    activePIP: 4,
    openCAP: 6,
    manager: "Rohan Iyer",
  },
  {
    name: "Messaging - General",
    channel: "messaging",
    headcount: 78,
    activePIP: 2,
    openCAP: 3,
    manager: "Helena Park",
  },
  {
    name: "Messaging - Hosting",
    channel: "messaging",
    headcount: 54,
    activePIP: 1,
    openCAP: 2,
    manager: "Helena Park",
  },
  {
    name: "Messaging - Sales",
    channel: "messaging",
    headcount: 70,
    activePIP: 3,
    openCAP: 4,
    manager: "Helena Park",
  },
  {
    name: "Messaging - Email Support",
    channel: "messaging",
    headcount: 62,
    activePIP: 2,
    openCAP: 3,
    manager: "Marcia Lin",
  },
  {
    name: "Messaging - Account Support",
    channel: "messaging",
    headcount: 58,
    activePIP: 1,
    openCAP: 2,
    manager: "Marcia Lin",
  },
  {
    name: "Customer Development Team",
    channel: "cdt",
    headcount: 110,
    activePIP: 4,
    openCAP: 5,
    manager: "Rohan Iyer",
  },
];

export const channelLabel = {
  voice: "Voice",
  messaging: "Messaging",
  cdt: "CDT",
};
