/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupervisorIndexRouteImport } from './routes/supervisor/index'
import { Route as PipIndexRouteImport } from './routes/pip/index'
import { Route as CapIndexRouteImport } from './routes/cap/index'
import { Route as PipCandidatesRouteImport } from './routes/pip/candidates'
import { Route as PipApprovalsRouteImport } from './routes/pip/approvals'
import { Route as CapNewRouteImport } from './routes/cap/new'
import { Route as CapExceptionsRouteImport } from './routes/cap/exceptions'
import { Route as PipCasesIndexRouteImport } from './routes/pip/cases.index'
import { Route as CapCasesIndexRouteImport } from './routes/cap/cases.index'
import { Route as SupervisorPipReviewRouteImport } from './routes/supervisor/pip.review'
import { Route as SupervisorPipInitiateRouteImport } from './routes/supervisor/pip.initiate'
import { Route as SupervisorPipFailureRouteImport } from './routes/supervisor/pip.failure'
import { Route as SupervisorPipDocumentRouteImport } from './routes/supervisor/pip.document'
import { Route as SupervisorPipClosureRouteImport } from './routes/supervisor/pip.closure'
import { Route as SupervisorPipCandidatesRouteImport } from './routes/supervisor/pip.candidates'
import { Route as PipCasesCaseIdRouteImport } from './routes/pip/cases.$caseId'
import { Route as CapCasesCaseIdRouteImport } from './routes/cap/cases.$caseId'

const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorIndexRoute = SupervisorIndexRouteImport.update({
  id: '/supervisor/',
  path: '/supervisor/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipIndexRoute = PipIndexRouteImport.update({
  id: '/pip/',
  path: '/pip/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapIndexRoute = CapIndexRouteImport.update({
  id: '/cap/',
  path: '/cap/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipCandidatesRoute = PipCandidatesRouteImport.update({
  id: '/pip/candidates',
  path: '/pip/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const PipApprovalsRoute = PipApprovalsRouteImport.update({
  id: '/pip/approvals',
  path: '/pip/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const CapNewRoute = CapNewRouteImport.update({
  id: '/cap/new',
  path: '/cap/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CapExceptionsRoute = CapExceptionsRouteImport.update({
  id: '/cap/exceptions',
  path: '/cap/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PipCasesIndexRoute = PipCasesIndexRouteImport.update({
  id: '/pip/cases/',
  path: '/pip/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapCasesIndexRoute = CapCasesIndexRouteImport.update({
  id: '/cap/cases/',
  path: '/cap/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorPipReviewRoute = SupervisorPipReviewRouteImport.update({
  id: '/supervisor/pip/review',
  path: '/supervisor/pip/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorPipInitiateRoute = SupervisorPipInitiateRouteImport.update({
  id: '/supervisor/pip/initiate',
  path: '/supervisor/pip/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorPipFailureRoute = SupervisorPipFailureRouteImport.update({
  id: '/supervisor/pip/failure',
  path: '/supervisor/pip/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorPipDocumentRoute = SupervisorPipDocumentRouteImport.update({
  id: '/supervisor/pip/document',
  path: '/supervisor/pip/document',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorPipClosureRoute = SupervisorPipClosureRouteImport.update({
  id: '/supervisor/pip/closure',
  path: '/supervisor/pip/closure',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorPipCandidatesRoute = SupervisorPipCandidatesRouteImport.update({
  id: '/supervisor/pip/candidates',
  path: '/supervisor/pip/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const PipCasesCaseIdRoute = PipCasesCaseIdRouteImport.update({
  id: '/pip/cases/$caseId',
  path: '/pip/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CapCasesCaseIdRoute = CapCasesCaseIdRouteImport.update({
  id: '/cap/cases/$caseId',
  path: '/cap/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cap/exceptions': typeof CapExceptionsRoute
  '/cap/new': typeof CapNewRoute
  '/pip/approvals': typeof PipApprovalsRoute
  '/pip/candidates': typeof PipCandidatesRoute
  '/cap/': typeof CapIndexRoute
  '/pip/': typeof PipIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
  '/cap/cases/$caseId': typeof CapCasesCaseIdRoute
  '/pip/cases/$caseId': typeof PipCasesCaseIdRoute
  '/supervisor/pip/candidates': typeof SupervisorPipCandidatesRoute
  '/supervisor/pip/closure': typeof SupervisorPipClosureRoute
  '/supervisor/pip/document': typeof SupervisorPipDocumentRoute
  '/supervisor/pip/failure': typeof SupervisorPipFailureRoute
  '/supervisor/pip/initiate': typeof SupervisorPipInitiateRoute
  '/supervisor/pip/review': typeof SupervisorPipReviewRoute
  '/cap/cases/': typeof CapCasesIndexRoute
  '/pip/cases/': typeof PipCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cap/exceptions': typeof CapExceptionsRoute
  '/cap/new': typeof CapNewRoute
  '/pip/approvals': typeof PipApprovalsRoute
  '/pip/candidates': typeof PipCandidatesRoute
  '/cap': typeof CapIndexRoute
  '/pip': typeof PipIndexRoute
  '/supervisor': typeof SupervisorIndexRoute
  '/cap/cases/$caseId': typeof CapCasesCaseIdRoute
  '/pip/cases/$caseId': typeof PipCasesCaseIdRoute
  '/supervisor/pip/candidates': typeof SupervisorPipCandidatesRoute
  '/supervisor/pip/closure': typeof SupervisorPipClosureRoute
  '/supervisor/pip/document': typeof SupervisorPipDocumentRoute
  '/supervisor/pip/failure': typeof SupervisorPipFailureRoute
  '/supervisor/pip/initiate': typeof SupervisorPipInitiateRoute
  '/supervisor/pip/review': typeof SupervisorPipReviewRoute
  '/cap/cases': typeof CapCasesIndexRoute
  '/pip/cases': typeof PipCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/cap/exceptions': typeof CapExceptionsRoute
  '/cap/new': typeof CapNewRoute
  '/pip/approvals': typeof PipApprovalsRoute
  '/pip/candidates': typeof PipCandidatesRoute
  '/cap/': typeof CapIndexRoute
  '/pip/': typeof PipIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
  '/cap/cases/$caseId': typeof CapCasesCaseIdRoute
  '/pip/cases/$caseId': typeof PipCasesCaseIdRoute
  '/supervisor/pip/candidates': typeof SupervisorPipCandidatesRoute
  '/supervisor/pip/closure': typeof SupervisorPipClosureRoute
  '/supervisor/pip/document': typeof SupervisorPipDocumentRoute
  '/supervisor/pip/failure': typeof SupervisorPipFailureRoute
  '/supervisor/pip/initiate': typeof SupervisorPipInitiateRoute
  '/supervisor/pip/review': typeof SupervisorPipReviewRoute
  '/cap/cases/': typeof CapCasesIndexRoute
  '/pip/cases/': typeof PipCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/cap/exceptions'
    | '/cap/new'
    | '/pip/approvals'
    | '/pip/candidates'
    | '/cap/'
    | '/pip/'
    | '/supervisor/'
    | '/cap/cases/$caseId'
    | '/pip/cases/$caseId'
    | '/supervisor/pip/candidates'
    | '/supervisor/pip/closure'
    | '/supervisor/pip/document'
    | '/supervisor/pip/failure'
    | '/supervisor/pip/initiate'
    | '/supervisor/pip/review'
    | '/cap/cases/'
    | '/pip/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/cap/exceptions'
    | '/cap/new'
    | '/pip/approvals'
    | '/pip/candidates'
    | '/cap'
    | '/pip'
    | '/supervisor'
    | '/cap/cases/$caseId'
    | '/pip/cases/$caseId'
    | '/supervisor/pip/candidates'
    | '/supervisor/pip/closure'
    | '/supervisor/pip/document'
    | '/supervisor/pip/failure'
    | '/supervisor/pip/initiate'
    | '/supervisor/pip/review'
    | '/cap/cases'
    | '/pip/cases'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/cap/exceptions'
    | '/cap/new'
    | '/pip/approvals'
    | '/pip/candidates'
    | '/cap/'
    | '/pip/'
    | '/supervisor/'
    | '/cap/cases/$caseId'
    | '/pip/cases/$caseId'
    | '/supervisor/pip/candidates'
    | '/supervisor/pip/closure'
    | '/supervisor/pip/document'
    | '/supervisor/pip/failure'
    | '/supervisor/pip/initiate'
    | '/supervisor/pip/review'
    | '/cap/cases/'
    | '/pip/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CapExceptionsRoute: typeof CapExceptionsRoute
  CapNewRoute: typeof CapNewRoute
  PipApprovalsRoute: typeof PipApprovalsRoute
  PipCandidatesRoute: typeof PipCandidatesRoute
  CapIndexRoute: typeof CapIndexRoute
  PipIndexRoute: typeof PipIndexRoute
  SupervisorIndexRoute: typeof SupervisorIndexRoute
  CapCasesCaseIdRoute: typeof CapCasesCaseIdRoute
  PipCasesCaseIdRoute: typeof PipCasesCaseIdRoute
  SupervisorPipCandidatesRoute: typeof SupervisorPipCandidatesRoute
  SupervisorPipClosureRoute: typeof SupervisorPipClosureRoute
  SupervisorPipDocumentRoute: typeof SupervisorPipDocumentRoute
  SupervisorPipFailureRoute: typeof SupervisorPipFailureRoute
  SupervisorPipInitiateRoute: typeof SupervisorPipInitiateRoute
  SupervisorPipReviewRoute: typeof SupervisorPipReviewRoute
  CapCasesIndexRoute: typeof CapCasesIndexRoute
  PipCasesIndexRoute: typeof PipCasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/': {
      id: '/supervisor/'
      path: '/supervisor'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof SupervisorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pip/': {
      id: '/pip/'
      path: '/pip'
      fullPath: '/pip/'
      preLoaderRoute: typeof PipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cap/': {
      id: '/cap/'
      path: '/cap'
      fullPath: '/cap/'
      preLoaderRoute: typeof CapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pip/candidates': {
      id: '/pip/candidates'
      path: '/pip/candidates'
      fullPath: '/pip/candidates'
      preLoaderRoute: typeof PipCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pip/approvals': {
      id: '/pip/approvals'
      path: '/pip/approvals'
      fullPath: '/pip/approvals'
      preLoaderRoute: typeof PipApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cap/new': {
      id: '/cap/new'
      path: '/cap/new'
      fullPath: '/cap/new'
      preLoaderRoute: typeof CapNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cap/exceptions': {
      id: '/cap/exceptions'
      path: '/cap/exceptions'
      fullPath: '/cap/exceptions'
      preLoaderRoute: typeof CapExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pip/cases/': {
      id: '/pip/cases/'
      path: '/pip/cases'
      fullPath: '/pip/cases/'
      preLoaderRoute: typeof PipCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cap/cases/': {
      id: '/cap/cases/'
      path: '/cap/cases'
      fullPath: '/cap/cases/'
      preLoaderRoute: typeof CapCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/pip/review': {
      id: '/supervisor/pip/review'
      path: '/supervisor/pip/review'
      fullPath: '/supervisor/pip/review'
      preLoaderRoute: typeof SupervisorPipReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/pip/initiate': {
      id: '/supervisor/pip/initiate'
      path: '/supervisor/pip/initiate'
      fullPath: '/supervisor/pip/initiate'
      preLoaderRoute: typeof SupervisorPipInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/pip/failure': {
      id: '/supervisor/pip/failure'
      path: '/supervisor/pip/failure'
      fullPath: '/supervisor/pip/failure'
      preLoaderRoute: typeof SupervisorPipFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/pip/document': {
      id: '/supervisor/pip/document'
      path: '/supervisor/pip/document'
      fullPath: '/supervisor/pip/document'
      preLoaderRoute: typeof SupervisorPipDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/pip/closure': {
      id: '/supervisor/pip/closure'
      path: '/supervisor/pip/closure'
      fullPath: '/supervisor/pip/closure'
      preLoaderRoute: typeof SupervisorPipClosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor/pip/candidates': {
      id: '/supervisor/pip/candidates'
      path: '/supervisor/pip/candidates'
      fullPath: '/supervisor/pip/candidates'
      preLoaderRoute: typeof SupervisorPipCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pip/cases/$caseId': {
      id: '/pip/cases/$caseId'
      path: '/pip/cases/$caseId'
      fullPath: '/pip/cases/$caseId'
      preLoaderRoute: typeof PipCasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cap/cases/$caseId': {
      id: '/cap/cases/$caseId'
      path: '/cap/cases/$caseId'
      fullPath: '/cap/cases/$caseId'
      preLoaderRoute: typeof CapCasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CapExceptionsRoute: CapExceptionsRoute,
  CapNewRoute: CapNewRoute,
  PipApprovalsRoute: PipApprovalsRoute,
  PipCandidatesRoute: PipCandidatesRoute,
  CapIndexRoute: CapIndexRoute,
  PipIndexRoute: PipIndexRoute,
  SupervisorIndexRoute: SupervisorIndexRoute,
  CapCasesCaseIdRoute: CapCasesCaseIdRoute,
  PipCasesCaseIdRoute: PipCasesCaseIdRoute,
  SupervisorPipCandidatesRoute: SupervisorPipCandidatesRoute,
  SupervisorPipClosureRoute: SupervisorPipClosureRoute,
  SupervisorPipDocumentRoute: SupervisorPipDocumentRoute,
  SupervisorPipFailureRoute: SupervisorPipFailureRoute,
  SupervisorPipInitiateRoute: SupervisorPipInitiateRoute,
  SupervisorPipReviewRoute: SupervisorPipReviewRoute,
  CapCasesIndexRoute: CapCasesIndexRoute,
  PipCasesIndexRoute: PipCasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
